apiVersion: apps/v1
kind: Deployment
metadata:
name: employee
spec:
replicas: 3
selector:
matchLabels:
app: hello-world
template:
metadata:
labels:
app: hello-world
spec:
containers:
- name: hello-world
image: kumarartech/tomcat:$BUILD_NUMBER
ports:
- containerPort: 8081
protocol: TCP